//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommentsSystemMVC5.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubComment
    {
        public int SubComID { get; set; }
        public string CommentMsg { get; set; }
        public Nullable<System.DateTime> CommentedDate { get; set; }
        public Nullable<int> ComID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
